FROM golang:alpine

RUN apk update && \
apk upgrade && \
apk add --no-cache git && \ 
go get github.com/langzhenjun/shadowsocks-go/cmd/shadowsocks-server

ADD https://github.com/golang/net/archive/master.zip $GOPATH/src/golang.org/x/net
ADD https://github.com/golang/crypto/archive/master.zip $GOPATH/src/golang.org/x/crypto

EXPOSE 8080

ENTRYPOINT ["shadowsocks-server"]